spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unit-test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    hikari:
      pool-name: Unit-Test-Pool
      maximum-pool-size: 3
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 3000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9999
  error:
    include-message: always